## buildspec.yml
version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
    dynamic:
      buildspec:
        - cypress/buildspec-cypress.yml
      env:
        variables:
          SPEC_DIR:
            - "cypress/e2e/1-getting-started/*.cy.js"
            - "cypress/e2e/2-advanced-examples/*.cy.js"
            - "cypress/e2e/3-advanced-examples/*.cy.js"
            - "cypress/e2e/4-advanced-examples/*.cy.js"
            # - "cypress/e2e/**/*.cy.js"
          REGION:
            - "main"
            - "ue1"
            # - "uw2"

# batch:
#   fast-fail: true
#   build-list:
#     - identifier: "1_getting_started"
#       buildspec: cypress/buildspec-ui.yml
#       env:
#         variables:
#           SPEC_DIR: "cypress/e2e/1-getting-started/*.cy.js"
#       ignore-failure: false
#     - identifier: "2_advanced_examples"
#       buildspec: cypress/buildspec-cypress.yml
#       env:
#         variables:
#           SPEC_DIR: "cypress/e2e/2-advanced-examples/*.cy.js"
#       ignore-failure: true
#     - identifier: "3_advanced_examples"
#       buildspec: cypress/buildspec-cypress.yml
#       env:
#         variables:
#           SPEC_DIR: "cypress/e2e/3-advanced-examples/*.cy.js"
#       ignore-failure: true
#     - identifier: "4_advanced_examples"
#       buildspec: cypress/buildspec-cypress.yml
#       env:
#         variables:
#           SPEC_DIR: "cypress/e2e/4-advanced-examples/*.cy.js"
#       ignore-failure: true

