## buildspec.yml
version: 0.2

batch:
  fast-fail: true
  build-list:
    - identifier: "1_getting_started"
      buildspec: cypress/buildspec-batch.yml
      env:
        variables:
          SPEC_DIR: "cypress/e2e/1-getting-started/*.cy.js"
      ignore-failure: false
    - identifier: "2_advanced_examples"
      buildspec: cypress/buildspec-batch.yml
      env:
        variables:
          SPEC_DIR: "cypress/e2e/2-advanced-examples/*.cy.js"
      ignore-failure: true
    - identifier: "3_advanced_examples"
      buildspec: cypress/buildspec-batch.yml
      env:
        variables:
          SPEC_DIR: "cypress/e2e/3-advanced-examples/*.cy.js"
      ignore-failure: true
    - identifier: "4_advanced_examples"
      buildspec: cypress/buildspec-batch.yml
      env:
        variables:
          SPEC_DIR: "cypress/e2e/4-advanced-examples/*.cy.js"
      ignore-failure: true

