## buildspec.yml
version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: UITesting
      ignore-failure: false
      debub-session: false
      buildspec: cypress/buildspec-batch.yml

